{{- if not (eq .Values.minReplicas .Values.maxReplicas) }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "tmpl.fullname" . }}
  labels:
    {{- include "tmpl.labels" (dict "context" . "component" .Values.name "name" .Values.name) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tmpl.fullname" . }}
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80 # var?
{{- end }}
