apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tmpl.serviceAccountName" . }}
  labels:
    {{- include "tmpl.labels" (dict "context" . "component" .Values.name "name" .Values.name) | nindent 4 }}
