apiVersion: v1
kind: Service
metadata:
  name: {{ include "tmpl.fullname" . }}
  labels:
    {{- include "tmpl.labels" (dict "context" . "component" .Values.name "name" .Values.name) | nindent 4 }}
spec:
  type: ClusterIP # var?
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tmpl.selectorLabels" (dict "context" . "name" .Values.name) | nindent 4 }}
